spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jumpstart
    username: root
    password: harris542002##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: DEBUG